fix: updated stack definition
terraform-ibm-modules/stack-retrieval-augmented-generation pull request #117
Opened 2024-05-30 17:05 UTC by Ak-sky

### Description

Updated stack definition to have input for `existing_kms_instance_crn`.
### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-30 17:20 UTC, ocofaigh requested changes
The new variable needs to be added into `ibm_catalog.json`

2024-05-30 17:34 UTC, Ak-sky commented
/run pipeline

2024-05-30 18:01 UTC, Ak-sky commented
/run pipeline

2024-05-31 06:18 UTC, Ak-sky commented
/run pipeline

2024-05-31 08:27 UTC, ocofaigh approved these changes

2024-05-31 09:05 UTC, vburckhardt commented on ibm_catalog.json
> +							"description": "The CRN of an existing KMS instance to use in this solution. If not set, a new KP instance is provisioned.",
KP -> Key Protect

2024-05-31 09:05 UTC, merged

2024-05-31 09:06 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/releases/tag/v1.1.0)
- `v1.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: