fix: add extra stack outputs and inputs
terraform-ibm-modules/stack-retrieval-augmented-generation pull request #202
Opened 2024-10-02 15:00 UTC by akocbek

### Description

issues: 
- https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/210
- https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/212
- https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/203

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-10-03 10:26 UTC, akocbek commented
/run pipeline

2024-10-03 15:04 UTC, akocbek commented
/run pipeline

2024-10-03 17:05 UTC, akocbek commented
/run pipeline

2024-10-04 09:24 UTC, akocbek commented
/run pipeline

2024-10-04 13:30 UTC, daniel-butler-irl approved these changes
Stack defs look good, you might want someone else to take a look at the diagram, I cannot comment if is correct or not

2024-11-28 14:52 UTC, ocofaigh requested changes
@akocbek see comments

2024-11-28 14:52 UTC, ocofaigh commented on solutions/basic/stack_definition.json
> +    },
remove `log_analysis_crn` and `log_analysis_guid` - the stack no longer deploys log analysis

2024-11-28 14:52 UTC, ocofaigh commented on solutions/standard/stack_definition.json
> +      "value": "ref:../members/Essential Security - Logging Monitoring Activity Tracker/outputs/log_analysis_guid"
remove `log_analysis_crn` and `log_analysis_guid` - the stack no longer deploys log analysis

2024-12-03 13:56 UTC, akocbek commented
/run pipeline

2024-12-03 14:15 UTC, akocbek commented
/run pipeline

2024-12-03 17:43 UTC, akocbek commented
/run pipeline

2024-12-03 20:23 UTC, akocbek commented
/run pipeline

2024-12-04 11:15 UTC, ocofaigh commented
The pipeline is failing due to known issues with projects race condition. I'm doing a manual test using your branch, and if the outputs look good, Ill proceed to force merge this

2024-12-04 14:43 UTC, merged

2024-12-04 14:44 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.1.1 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/releases/tag/v2.1.1)
- `v2.1.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: