feat: use existing scc instance
terraform-ibm-modules/stack-retrieval-augmented-generation pull request #221
Opened 2024-10-22 16:25 UTC by kierramarie

### Description

Updated version locator to newest version of SCC and included variable for existing SCC instance.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-10-22 17:48 UTC, kierramarie commented
/run pipeline

2024-10-29 14:44 UTC, kierramarie commented
Test failed because of projects limit, but the SCC part of the project was successfully deployed.

2024-11-13 16:46 UTC, kierramarie commented
/run pipeline

2024-12-11 15:47 UTC, kierramarie commented
run pipeline

2024-12-11 19:29 UTC, ocofaigh commented
@kierramarie editing the comment wont trigger pipeline. Needs a new comment. I'll leave one now to trigger..

2024-12-11 19:30 UTC, ocofaigh requested changes
Oh but first it seems as if your missing the new variable in the ibm_catalog.json

2024-12-12 15:03 UTC, kierramarie commented
/run pipeline

2024-12-12 20:47 UTC, ocofaigh requested changes
Can we update the existing resources test to test existing SCC so we test the feature in the stack?

PS: Projects seems a little unstable at the moment so I suspect thats why tests are failing. Lets see what tests look like after your next commit

2024-12-17 22:03 UTC, kierramarie commented
/run pipeline

2024-12-19 17:43 UTC, kierramarie commented
blocked by https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/pull/242

2025-04-09 18:11 UTC, kierramarie commented
/run pipeline

2025-04-25 11:38 UTC, ocofaigh commented
No longer a prioroty

2025-04-25 11:38 UTC, closed without merging